// <auto-generated />
namespace University_API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Student_Migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Student_Migration));
        
        string IMigrationMetadata.Id
        {
            get { return "201812140111325_Student_Migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
